import java.awt.*;
import java.awt.event.*;
import java.io.*;
import javax.swing.*;
import sun.audio.*;

//Hra Balóny
/* Balóny rôznych farieb stúpajú zdola nahor.
 * Hráč má v časovom limite prepichnúť čo najviac balónov.
 * Rôzne farby = rôzny počet bodov. 
 * Občas sa zjaví balón s bonusovým účinkom (počet bodov sa zdvojnásobí).
 * Občas sa zjaví nulovací balón (bodové skóre sa vynuluje).
 * Počas hry hrá príjemná pesnička a po kliknutí na balóny zaznie zvuk.
 * Pozadie a obrázok som pridala pomocou jLabel-u.
 */

/**
 * @author Viktória Ševčíková AIBC09 
 */
public class Okno extends javax.swing.JFrame implements ActionListener{
    private Timer casovac;
    private int cas; 
    private int delay;
    
    private int pocetB = 20; //počet balónov
    private AudioStream aS;
    
    Balon[] balony;
    SpecialnyBalon sb;
    
    /**
     * Creates new form Okno
     */
    public Okno() {
        //nastavenie pozadia na bielu farbu
        getContentPane().setBackground(Color.WHITE);
        casovac = new Timer(800,this);   
        pridanieKomponentov(); 
        
        sb = new SpecialnyBalon(this, 30);
        add(sb);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Balóny <3");
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFont(new java.awt.Font("Comic Sans MS", 0, 10)); // NOI18N
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clouds.JPG"))); // NOI18N
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));

        jButton1.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jButton1.setText("ŠTART");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 0, 15)); // NOI18N
        jLabel2.setText("Zostáva :");

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 0, 15)); // NOI18N
        jLabel4.setText("Skóre :");

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/up3.JPG"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 680, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(5, 5, 5)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73))
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //START zapne sa casovac na odpočítavanie sekúnd, nastaví sa cas aj skore, 
        //ale tlačidlo START je dostupné iba ak je cas menší ako 0
        if(cas<0){
            jButton1.setDefaultCapable(true);
            casovac.start();
            spustiZvuk();
            cas = 100;
            balony[0].setSkore();
        }else{     
            jButton1.setDefaultCapable(false);
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    //pri otvorení okna sa hneď spustí hra
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        casovac.start();
        spustiZvuk();
        cas = 100;
        balony[0].setSkore();
    }//GEN-LAST:event_formWindowOpened
     /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Okno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Okno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Okno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Okno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Okno().setVisible(true);
            }
        });
    } 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
 
    @Override
    public void actionPerformed(ActionEvent e) {

       for (int i = 0; i < pocetB-1; i++){        
        balony[i].actionPerformed(e); 
       }
       //iba ak bude cas deliteľný 30 tak sa spustí specialny balon
        if(cas%30==0){
            sb.actionPerformed(e);
        }
        //každé tiknutie sa bude meniť cas aj skore a znižuje sa počet casu
        jLabel3.setText(""+cas+" sekúnd");
        jLabel5.setText(""+balony[0].getSkore());
        cas--;
          
        //ak bude 0 tak sa zastaví casovac na odpočítavanie casu, aj casovac balónov, vypne sa pesnička a vyskočí dialógove okno
        if(cas <0){
            casovac.stop();
            
             for (int i = 0; i < pocetB-1; i++){
                 balony[i].stop();     
             }
            sb.stop();
            AudioPlayer.player.stop(aS);
            
            int odpoved = JOptionPane.showConfirmDialog(this, "Super, tvoje skóre je: "+ balony[0].getSkore()
                        + "\nChceš si zahrať ešte raz?", "Vypršal čas", JOptionPane.OK_CANCEL_OPTION);

                if (odpoved == JOptionPane.CANCEL_OPTION)
                    System.exit(1);
            }                   
        }
    
    //vlastná metóda na spustenie pesničky
    public void spustiZvuk(){
        InputStream in = null;
        try {
            in = new FileInputStream("marriedLifeUp.wav");
            System.out.println("Spustila sa hudba");
            aS = new AudioStream(in);
        } catch (IOException ex) {
        System.out.println("Nenasla sa");
        }

        AudioPlayer.player.start(aS);
    }
    
    //vlastná metóda na vytvorenie balónov,parametre, ktoré vstupujú do konštruktora sú JFrame a rýchlosť(delay)
    public void pridanieKomponentov() {
        balony = new Balon[pocetB-1];
        
        for (int i = 0; i < pocetB-1; i++)
        {
            delay = (int)(10+Math.random()*100);
            balony[i] = new Balon(this,delay);

            add(balony[i]);
            repaint();
        }
    } 
} 
   

